runtime: python312
entrypoint: gunicorn -b :$PORT app:app

instance_class: F1

env_variables:
  FLASK_ENV: production
  # Add HUGGING_FACE_TOKEN in GCP Console Secret Manager

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 10
  min_idle_instances: 0
  max_idle_instances: 1

# GDPR-compliant: No session affinity (stateless)
session_affinity: false

# Handlers
handlers:
- url: /.*
  script: auto
  secure: always
